#### [基本使用](https://github.com/zyy782/yuanyuan.github.io/blob/main/Promise/02.js)    
1. 创建Promise对象
2. 执行异步操作
3. 成功, 调用 resolve(value)    
  失败, 调用 reject(reason)   
![H40OXIX_MS9N{0YVD ~2 6X](https://user-images.githubusercontent.com/71962217/132632834-38f7aecc-74f0-43e6-9275-0394a8155891.png)


根据[基本使用](https://github.com/zyy782/yuanyuan.github.io/blob/main/Promise/02.js)输出结果，可以看出：   
(resolve, reject)=>{}为执行器函数，是同步回调

#### 为什么使用promise
1. <span style="color:red">**指定回调函数的方式更加灵活**</span>:    
   旧的: 必须在启动异步任务前指定   
   promise: 启动异步任务 => 返回promie对象 => 给promise对象绑定回调函数(甚至可以在异步任务结束后指定)    
   比如说，我可以在拿到promise结果之后的时间再去回调 ,以 [基本使用](https://github.com/zyy782/yuanyuan.github.io/blob/main/Promise/02.js) 中的代码为例，改为下面的形式依旧可以取得结果   
   ```
   setTimeout(() => {
    p.then(value => { //onResolved
        console.log("成功的回调" + value)
    }, reason => { //onRejected
        console.log("失败的回调" + reason)
    }).catch(reason => {
        console.log("接收到失败的reason数据" + reason)
    })

   }, 3000)
   ```
2. <span style="color:red">**解决回调地狱**</span>:    
    回调地狱，即 回调函数嵌套调用, 外部回调函数异步执行的结果是嵌套的回调函数执行的条件，回调函数层层嵌套形成“回调地狱”      
    缺点：不便于阅读 / 不便于异常处理   
    **解决方案---->promise链式调用    
    终极解决方案-----> async/await**   
    [查看案例](https://github.com/zyy782/yuanyuan.github.io/blob/main/Promise/02%2B.js)
